# Generated by Django 5.1.1 on 2024-09-25 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_id', models.CharField(max_length=100)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('TR', '训练中'), ('AV', '可用'), ('FA', '失败')], default='TR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SynthesizedAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('audio_file', models.FileField(upload_to='synthesized_audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voice_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voice_app.voicemodel')),
            ],
        ),
    ]
