# Generated by Django 5.1.1 on 2024-09-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicemodel',
            name='name',
            field=models.CharField(default='model-<function now at 0x104b0d300>', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voicemodel',
            name='speaker_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='voicemodel',
            name='status',
            field=models.CharField(choices=[('TR', '训练中'), ('AV', '可用'), ('FA', '失败')], default='AV', max_length=2),
        ),
        migrations.AlterField(
            model_name='voicemodel',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
